add the install subcommand in the makefile
Hyperledger-TWGC/tape pull request #137
Opened 2021-01-29 09:02 UTC by hellosmallstone

install subcommand will copy the binary to the local GOBIN

Signed-off-by: wuxu <wuxu1103@163.com>

2021-01-29 09:06 UTC, SamYuan1990 requested changes

2021-01-29 09:06 UTC, SamYuan1990 commented on Makefile
> +.PHONY: install
if `./tape` not exist?

2021-01-29 09:09 UTC, SamYuan1990 submitted a review, later dismissed

2021-01-29 15:36 UTC, hellosmallstone commented
I don't know why the GOBIN is empty in the CI environment. So I added the judgement of whether GOBIN is empty.

2021-01-29 15:41 UTC, SamYuan1990 submitted a review, later dismissed

2021-01-29 15:41 UTC, SamYuan1990 commented on Makefile
> +	@echo "Warning: GOBIN is not configured!"
@echo "Warning: GOBIN is not configured! You are able to copy tape binary file to your $PATH" 

这类描述？我不确定windows下是不是$PATH.
另外考虑下755这样的文件权限？

2021-01-29 16:35 UTC, guoger commented on Makefile
> +	@echo "Warning: GOBIN is not configured!"
应该可以跑`go install`吧？

2021-01-29 16:38 UTC, guoger commented on Makefile
> +	@echo "Warning: GOBIN is not configured!"
e.g.:
```make
.PHONY: install
install:
	@echo "Install tape"
	go install -tags "$(GO_TAGS)" -ldflags "$(GO_LDFLAGS)" ./cmd/tape
```

2021-01-29 16:42 UTC, guoger commented
also, we should add `make basic-check` to run gofmt and linter, for example: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-gofmt.sh and https://github.com/hyperledger/fabric/blob/bbdb4e7929e4ed32024a42d7593e4f4db5fbc39a/Makefile#L109

2021-02-07 09:49 UTC, guoger approved these changes
`basic-checks` should be extracted to its own job, preferably executed **before** everything else

2021-02-07 09:50 UTC, merged