reslove #149
Hyperledger-TWGC/tape pull request #151
Opened 2021-02-10 15:09 UTC by SamYuan1990

Signed-off-by: SamYuan1990 <yy19902439@126.com>

2021-02-17 08:39 UTC, guoger commented on e2e/mock/orderer.go
> +}
what's this for?

2021-02-17 14:46 UTC, SamYuan1990 commented on e2e/mock/orderer.go
> +}
为了做测试，往mock orderer的channel里塞dummy的对象。

2021-02-18 02:41 UTC, guoger commented on e2e/mock/orderer.go
> +}
但是 `Server.DummyBroadcast` 好像没有被调用？

2021-02-18 12:43 UTC, SamYuan1990 commented on e2e/mock/orderer.go
> +}
我少提交了个文件。。。QAQ

2021-03-02 09:56 UTC, hellosmallstone commented on pkg/infra/observer.go
> +	if ws.threshold < 0 {
ws.threshold <= 0 may be better

2021-03-02 11:25 UTC, SamYuan1990 commented on pkg/infra/observer.go
> +	if ws.threshold < 0 {
updated

2021-03-04 05:35 UTC, guoger requested changes
1. instead of coordinating `observer` go routines with awkward sync primitives, we could simply change `collector` to collect final states. `observer` just exits on signal
2. newly added test still does not cover this bug

2021-03-05 12:49 UTC, guoger requested changes

2021-03-05 12:49 UTC, guoger commented on e2e/mock/peer.go
> +func (p *Peer) Recovery() {
`Recover` or `Resume`

However, `Pause`/`Unpause` would read more straightforward

2021-03-05 12:49 UTC, guoger commented on e2e/mock/peer.go
> +	if !p.suspend {
this would not work:
1. there's race around access to `suspend`
2. once this for-loop is started, `Suspend` would not be effective.

2021-03-05 12:49 UTC, guoger commented on pkg/infra/block_collector.go
> +	committedTx    int
nit: this could grouped as
```go
totalP, thresholdP int
totalTx, committedTx int
```

2021-03-05 12:49 UTC, guoger commented on pkg/infra/block_collector.go
> +		committedTx:    0,
it's safe to omit this - use default value in Go whenever possible

2021-03-05 12:49 UTC, guoger commented on pkg/infra/observer.go
>  	for n < N {
as we discussed earlier, there's no need for `observer` to keep track of total num anymore, right?

2021-03-05 12:49 UTC, guoger commented on pkg/infra/observer.go
> +	defer wg.Done()
`observer` could simply exit on a signal `doneCh` now

2021-03-05 12:49 UTC, guoger commented on pkg/infra/block_collector.go
> +func (bc *BlockCollector) Commit(block uint64, txs int, now time.Time) (committed bool) {
it's not `now`, but `start`. also, why don't we pass this in at construction time?

furthermore, why couldn't we simply pass in `*Block` here?

2021-03-05 12:49 UTC, guoger commented on pkg/infra/block_collector.go
> +func NewBlockCollector(thresholdPeers int, totalPeers int, totalTx int) (*BlockCollector, error) {
like we discussed, `BlockCollector` now is just another `worker` in tape model, and should consume a "job" channel, on which block flows in.

2021-04-06 14:27 UTC, guoger requested changes
I'm under impression that you are trying to solve #165 and #149 at the same time? could you split this into separate PR so we could focus on one thing at a time.

2021-04-06 14:27 UTC, guoger commented on e2e/mock/peer.go
> +	p.Add(1)
first of all, there's race in accessing `wg`, from Go doc for `sync.WaitGroup`
> // Note that calls with a positive delta that occur when the counter is zero
> // must happen before a Wait.

secondly, the `p.Wait()` at line 36 blocks the process, which may block the sender of `TxC` when its buffer is full.

lastly, current implementation requires user to call `Suspend` only **before** server actually starts, which limits its use case. Although this is fine for now

2021-04-06 14:27 UTC, guoger commented on e2e/mock/orderer.go
> +}
i still don't think this method is necessary.. it can be easily done at caller side, where actual number is configurable.

2021-04-06 14:27 UTC, guoger commented on pkg/infra/block_collector.go
> +	bc.status = 1
what's this for? if we **have to** introduce an enum here (i hope not), please declare them

2021-04-09 13:03 UTC, SamYuan1990 commented on e2e/mock/orderer.go
> +}
这是用来测试模拟出块的函数，这样可以模拟peer直接接收出块的行为。使得Observer可以单独测试，而不需要在`mock`中再去从发交易从头来一遍了。我回头加个comments吧。

2021-04-11 11:42 UTC, yiwenlong commented on e2e/mock/peer.go
> +}
这里的 `Suspend` 和 `Resume` 函数的执行效果其实都是一样的，是否可以合并成一个函数，比如命名为 `Toggle`？

2021-04-13 11:46 UTC, SamYuan1990 commented on e2e/mock/peer.go
> +}
fixed.

2021-04-19 12:06 UTC, guoger requested changes

2021-04-19 12:06 UTC, guoger commented on e2e/mock/server.go
> +const MOCK_TX_SIZE = 1000
in Go, we use CamelCase for const, instead of SNAKE_CASE

2021-04-19 12:06 UTC, guoger commented on pkg/infra/block_collector.go
> +func (bc *BlockCollector) Commit(block *peer.DeliverResponse_FilteredBlock, finishCh chan struct{}, now time.Time) (committed bool) {
now this seems to be a burden to carry, let's remove.

2021-04-19 12:06 UTC, guoger commented on pkg/infra/block_collector_test.go
>  	Context("Sync Commit", func() {
remove

2021-04-22 12:03 UTC, guoger requested changes

2021-04-22 12:03 UTC, guoger commented on pkg/infra/observer_test.go
> +		<-finishCh
这个应该放到eventually里边把？

2021-04-22 12:03 UTC, guoger commented on pkg/infra/observer_test.go
> +		COMMIT_THRESHOLD := 2
camelCase

2021-04-22 12:03 UTC, guoger commented on pkg/infra/observer_test.go
> +		<-finishCh
eventually

2021-04-22 12:03 UTC, guoger commented on pkg/infra/observer_test.go
> +		Consistently(finishCh).ShouldNot(Receive())
是否需要增加consistently的等待时间？

2021-04-22 12:03 UTC, guoger commented on pkg/infra/block_collector_test.go
> +			<-finishCh
eventually

2021-04-22 12:03 UTC, guoger commented on pkg/infra/block_collector_test.go
> +			<-finishCh
eventually

2021-04-22 12:03 UTC, guoger commented on e2e/mock/peer.go
> +		case action := <-p.CtlCh:
rename: action -> pause

2021-04-24 03:41 UTC, SamYuan1990 commented on pkg/infra/observer_test.go
> +		Consistently(finishCh).ShouldNot(Receive())
不用吧， 参考Consistently的实现，有10ms的时间，然后看下log如下。看起来是等了10ms的？
```
// Consistently is useful in cases where you want to assert that something *does not happen* over a period of time.
// For example, you want to assert that a goroutine does *not* send data down a channel.  In this case, you could:
//
//   Consistently(channel).ShouldNot(Receive())
//
// Consistently's default duration is 100ms, and its default polling interval is 10ms
```

```
第一个case
•Time     0.00s Block      1    Tx     10        
Time     0.00s  Block      2    Tx     10        
Time     0.00s  Block      3    Tx     10        
Time     0.00s  Block      4    Tx     10        
Time     0.00s  Block      5    Tx     10        
Time     0.00s  Block      6    Tx     10        
Time     0.00s  Block      7    Tx     10        
Time     0.00s  Block      8    Tx     10        
Time     0.00s  Block      9    Tx     10        
Time     0.00s  Block     10    Tx     10        
Time     0.00s  Block     11    Tx     10        
Time     0.00s  Block     12    Tx     10        
Time     0.00s  Block     13    Tx     10        
Time     0.00s  Block     14    Tx     10        
Time     0.00s  Block     15    Tx     10        
Time     0.00s  Block     16    Tx     10        
Time     0.00s  Block     17    Tx     10        
Time     0.00s  Block     18    Tx     10        
Time     0.00s  Block     19    Tx     10        
Time     0.00s  Block     20    Tx     10        
Time     0.00s  Block     21    Tx     10        
Time     0.00s  Block     22    Tx     10        
Time     0.00s  Block     23    Tx     10        
Time     0.00s  Block     24    Tx     10        
Time     0.00s  Block     25    Tx     10        
Time     0.00s  Block     26    Tx     10        
Time     0.00s  Block     27    Tx     10        
Time     0.00s  Block     28    Tx     10        
Time     0.00s  Block     29    Tx     10        
Time     0.00s  Block     30    Tx     10        
Time     0.00s  Block     31    Tx     10        
Time     0.00s  Block     32    Tx     10        
Time     0.00s  Block     33    Tx     10        
Time     0.00s  Block     34    Tx     10        
Time     0.00s  Block     35    Tx     10        
Time     0.00s  Block     36    Tx     10        
Time     0.00s  Block     37    Tx     10        
Time     0.00s  Block     38    Tx     10        
Time     0.00s  Block     39    Tx     10        
Time     0.00s  Block     40    Tx     10        
Time     0.00s  Block     41    Tx     10        
Time     0.00s  Block     42    Tx     10        
Time     0.00s  Block     43    Tx     10        
Time     0.00s  Block     44    Tx     10        
Time     0.00s  Block     45    Tx     10        
Time     0.00s  Block     46    Tx     10        
Time     0.00s  Block     47    Tx     10        
Time     0.00s  Block     48    Tx     10        
Time     0.00s  Block     49    Tx     10        
Time     0.00s  Block     50    Tx     10        
Time     0.00s  Block     51    Tx     10        
Time     0.00s  Block     52    Tx     10        
Time     0.00s  Block     53    Tx     10        
Time     0.00s  Block     54    Tx     10        
Time     0.00s  Block     55    Tx     10        
Time     0.00s  Block     56    Tx     10        
Time     0.00s  Block     57    Tx     10        
Time     0.00s  Block     58    Tx     10        
Time     0.00s  Block     59    Tx     10        
Time     0.00s  Block     60    Tx     10        
Time     0.00s  Block     61    Tx     10        
Time     0.00s  Block     62    Tx     10        
Time     0.00s  Block     63    Tx     10        
Time     0.00s  Block     64    Tx     10        
Time     0.00s  Block     65    Tx     10        
Time     0.00s  Block     66    Tx     10        
Time     0.00s  Block     67    Tx     10        
Time     0.00s  Block     68    Tx     10        
Time     0.00s  Block     69    Tx     10        
Time     0.00s  Block     70    Tx     10        
Time     0.00s  Block     71    Tx     10        
Time     0.00s  Block     72    Tx     10        
Time     0.00s  Block     73    Tx     10        
Time     0.00s  Block     74    Tx     10        
Time     0.00s  Block     75    Tx     10        
Time     0.00s  Block     76    Tx     10        
Time     0.00s  Block     77    Tx     10        
Time     0.00s  Block     78    Tx     10        
Time     0.00s  Block     79    Tx     10        
Time     0.00s  Block     80    Tx     10        
Time     0.00s  Block     81    Tx     10        
Time     0.00s  Block     82    Tx     10        
Time     0.00s  Block     83    Tx     10        
Time     0.00s  Block     84    Tx     10        
Time     0.00s  Block     85    Tx     10        
Time     0.00s  Block     86    Tx     10        
Time     0.00s  Block     87    Tx     10        
Time     0.00s  Block     88    Tx     10        
Time     0.00s  Block     89    Tx     10        
Time     0.00s  Block     90    Tx     10        
Time     0.00s  Block     91    Tx     10        
Time     0.00s  Block     92    Tx     10        
Time     0.00s  Block     93    Tx     10        
Time     0.00s  Block     94    Tx     10        
Time     0.00s  Block     95    Tx     10        
Time     0.00s  Block     96    Tx     10        
Time     0.00s  Block     97    Tx     10        
Time     0.00s  Block     98    Tx     10        
Time     0.00s  Block     99    Tx     10        
Time     0.00s  Block    100    Tx     10
第二个case        
•Time     0.10s Block      1    Tx     10        
Time     0.10s  Block      2    Tx     10        
Time     0.10s  Block      3    Tx     10        
Time     0.10s  Block      4    Tx     10        
Time     0.10s  Block      5    Tx     10        
Time     0.10s  Block      6    Tx     10        
Time     0.10s  Block      7    Tx     10        
Time     0.10s  Block      8    Tx     10        
Time     0.10s  Block      9    Tx     10        
Time     0.10s  Block     10    Tx     10        
Time     0.10s  Block     11    Tx     10        
Time     0.10s  Block     12    Tx     10        
Time     0.10s  Block     13    Tx     10        
Time     0.10s  Block     14    Tx     10        
Time     0.10s  Block     15    Tx     10        
Time     0.10s  Block     16    Tx     10        
Time     0.10s  Block     17    Tx     10        
Time     0.10s  Block     18    Tx     10        
Time     0.10s  Block     19    Tx     10        
Time     0.10s  Block     20    Tx     10        
Time     0.10s  Block     21    Tx     10        
Time     0.10s  Block     22    Tx     10        
Time     0.10s  Block     23    Tx     10        
Time     0.10s  Block     24    Tx     10        
Time     0.10s  Block     25    Tx     10        
Time     0.10s  Block     26    Tx     10        
Time     0.10s  Block     27    Tx     10        
Time     0.10s  Block     28    Tx     10        
Time     0.10s  Block     29    Tx     10        
Time     0.10s  Block     30    Tx     10        
Time     0.10s  Block     31    Tx     10        
Time     0.10s  Block     32    Tx     10        
Time     0.10s  Block     33    Tx     10        
Time     0.10s  Block     34    Tx     10        
Time     0.10s  Block     35    Tx     10        
Time     0.10s  Block     36    Tx     10        
Time     0.10s  Block     37    Tx     10        
Time     0.10s  Block     38    Tx     10        
Time     0.10s  Block     39    Tx     10        
Time     0.10s  Block     40    Tx     10        
Time     0.10s  Block     41    Tx     10        
Time     0.10s  Block     42    Tx     10        
Time     0.10s  Block     43    Tx     10        
Time     0.10s  Block     44    Tx     10        
Time     0.10s  Block     45    Tx     10        
Time     0.10s  Block     46    Tx     10        
Time     0.10s  Block     47    Tx     10        
Time     0.10s  Block     48    Tx     10        
Time     0.10s  Block     49    Tx     10        
Time     0.10s  Block     50    Tx     10        
Time     0.10s  Block     51    Tx     10     [...]

2021-04-25 15:08 UTC, guoger requested changes

2021-04-25 15:08 UTC, guoger commented on e2e/mock/peer.go
> +	CtlCh := make(chan bool)
ctlCh (start with lower case)

2021-04-25 15:08 UTC, guoger commented on pkg/infra/block_collector_test.go
> +			Expect(finishCh).To(BeClosed())
this is redundant

2021-04-25 15:08 UTC, guoger commented on pkg/infra/block_collector_test.go
> +			Expect(finishCh).To(BeClosed())
this is redundant

2021-04-25 15:32 UTC, guoger approved these changes

2021-04-25 15:32 UTC, merged