BlockCollector detects repeated block
Hyperledger-TWGC/tape pull request #172
Opened 2021-04-08 10:25 UTC by hellosmallstone

BlockCollector detects repeated block from same observer and exclude it from block counting

https://github.com/Hyperledger-TWGC/tape/issues/165

Signed-off-by: wuxu <wuxu1103@163.com>

2021-04-08 11:37 UTC, guoger requested changes
I'm generally Okay with the approach, but with some minor concerns

2021-04-08 11:37 UTC, guoger commented on pkg/infra/block_collector.go
> +type BlockAddress struct {
`AddressedBlock` maybe?

and if we declare it with embedding:
```go
type AddressedBlock struct {
  *peer.FilteredBlock

  Address string
}
```
we could avoid some text changes in other part of code?

2021-04-08 11:37 UTC, guoger commented on pkg/infra/block_collector.go
> +	addressBlock       map[uint64]map[string]bool
i suppose only one of these two maps is sufficient?

also, with 16 peers and several millions of blocks, this map could take significant memory space. I think we do need gc here.

2021-04-08 11:37 UTC, guoger commented on pkg/infra/benchmark_test.go
> +		go func(num int) {
num -> idx

2021-04-13 12:06 UTC, SamYuan1990 commented on pkg/infra/block_collector_test.go
> +			block <- &infra.AddressedBlock{Address: "peer1", FilteredBlock: &peer.FilteredBlock{Number: 1, FilteredTransactions: make([]*peer.FilteredTransaction, 1)}}
em...提一个公共函数？

2021-04-13 12:06 UTC, SamYuan1990 commented on pkg/infra/block_collector_test.go
> +					block <- &infra.AddressedBlock{Address: fmt.Sprintf("peer%d", idx),
int转str就够了？

2021-04-19 12:21 UTC, guoger requested changes

2021-04-19 12:21 UTC, guoger commented on pkg/infra/block_collector.go
> +type BitMap struct {
`BitMap` could be moved to its own file/pkg

2021-04-19 12:21 UTC, guoger commented on pkg/infra/observer.go
> +	num     int
num -> index

2021-04-19 12:21 UTC, guoger commented on pkg/infra/block_collector.go
>  				delete(bc.registry, block.Number)
如果我们从registry中删除区块，那么如果下次收到重复的块，如果判断呢？

2021-04-20 13:41 UTC, SamYuan1990 commented on pkg/infra/block_collector.go
> +			panic("Can not make new bitmap for BlockCollector" + err.Error())
no panic

2021-04-20 13:41 UTC, SamYuan1990 commented on pkg/infra/block_collector.go
> +func (b *BitMap) Has(num int) bool {
bitmap的话会不会泄露？如果peer足够多？

2021-04-26 11:32 UTC, SamYuan1990 requested changes

2021-04-26 11:32 UTC, SamYuan1990 commented on pkg/infra/observer.go
> +	n := 0
remove n here?

2021-04-26 11:34 UTC, SamYuan1990 commented on pkg/infra/block_collector.go
> +func (bc *BlockCollector) commit(block *AddressedBlock, finishCh chan struct{}, totalTx int, now time.Time, printResult bool) {
加个 to do？

我在思考这里我们在这个函数里包括了。

构造其他对象。。。
方法。。。
常量对比。。。
提前退出。。。

我没想好怎么弄，但是感觉味道比较杂。

2021-04-28 12:38 UTC, SamYuan1990 approved these changes

2021-05-01 02:59 UTC, guoger commented on pkg/infra/block_collector.go
> +	Address int // source peer's number
it would be nice to rename this field to `PeerIdx`

2021-05-01 02:59 UTC, guoger approved these changes

2021-05-01 03:00 UTC, merged